name: Build and Deploy to Sandbox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Stamp artifact file name with commit hash
      run: |
        artifactName=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        newArtifactName=$(basename $artifactName | sed "s/.jar/-$commitHash.jar/")
        mv $artifactName target/$newArtifactName
        echo "ARTIFACT_NAME=target/$newArtifactName" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: mule-artifact
        path: ${{ env.ARTIFACT_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: mule-artifact

    - name: Deploy to Sandbox
      env:
        ANYPOINT_USERNAME: ${{ secrets.anypoint_platform_username }}
        ANYPOINT_PASSWORD: ${{ secrets.anypoint_platform_password }}
        ANYPOINT_ORG_ID: ${{ secrets.anypoint_organization_id }}
        ANYPOINT_ENV_ID: ${{ secrets.anypoint_environment_id }}
      run: |
        artifactName=$(ls target/*.jar | head -1)
        mvn mule:deploy \
          -Danypoint.username=$ANYPOINT_USERNAME \
          -Danypoint.password=$ANYPOINT_PASSWORD \
          -Dorganization.id=$ANYPOINT_ORG_ID \
          -Denvironment.id=$ANYPOINT_ENV_ID \
          -Dapplication.name=mule-app \
          -Dartifact.name=$artifactName
