name: Build and Deploy to Sandbox

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      # Clean and Build the project with Maven
      - name: Clean and Build
        run: |
          echo "Cleaning workspace..."
          mvn clean package

      # Deploy to CloudHub with Hardcoded Credentials
      - name: Deploy to CloudHub
        run: |
          echo "Deploying to CloudHub..."
          mvn deploy -DmuleDeploy \
            -Danypoint.username="Amir122323" \
            -Danypoint.password="Amir122306"
          echo "Deployment complete!"
