name: Build and Deploy to Sandbox

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Build with Maven
        run: mvn clean package -B --file pom.xml

      - name: Stamp Artifact File Name
        run: |
          artifactName1=$(find target -name "*.jar" | head -1)
          if [ -z "$artifactName1" ]; then
            echo "Error: No .jar file found in target directory."
            exit 1
          fi
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(echo $artifactName1 | sed "s/.jar/-$commitHash.jar/g")
          mv "$artifactName1" "$artifactName2"
          echo "Artifact renamed to $artifactName2"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli

      - name: Stop Current Application
        env:
          ANYPOINT_CLIENT_ID: "9aae268cfe3d4dce949376c9e754768b"
          ANYPOINT_CLIENT_SECRET: "0d841e724ADD480C88D2c5262CBdF2Ed"
        run: |
          anypoint-cli runtime-mgr cloudhub-application stop my-mule-app --environment sandbox

      - name: Deploy New Application
        env:
          ANYPOINT_CLIENT_ID: "9aae268cfe3d4dce949376c9e754768b"
          ANYPOINT_CLIENT_SECRET: "0d841e724ADD480C88D2c5262CBdF2Ed"
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn deploy -DmuleDeploy -DskipTests \
            -Dmule.artifact=$artifactName \
            -Danypoint.username="$ANYPOINT_CLIENT_ID" \
            -Danypoint.password="$ANYPOINT_CLIENT_SECRET"
