name: Build and Deploy to Sandbox

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      # Clean and Build the project with Maven
      - name: Clean and Build
        run: |
          echo "Cleaning workspace..."
          mvn clean package -DskipTests

      # Deploy to CloudHub with Hardcoded Credentials
      - name: Deploy to CloudHub
        run: |
          echo "Deploying to CloudHub..."
           mvn deploy -DmuleDeploy -DskipTests \
               -Danypoint.username="Amir122323" \
               -Danypoint.password="Amir122306" \
               -Danypoint.orgId="773ec503-c40f-4bb7-b891-34e11e40c432" \
               -Danypoint.envId="f5f5d0be-37e5-4b2c-ac52-e1a46c5b45ee" \
               -DapplicationName="mule-gitactions-$(date +%s)"

<<<<<<< HEAD
          echo "Deployment complete!"
=======
          echo "Deployment complete!"
>>>>>>> 70b78b223d70d3224a5263ef393a68241447ab85
